### ISSUE TITLE
Thunar Support (XFCE File manager)

### ISSUE THREAD

**Issue by tommasoxd** [PsykeDady/mowish#1]
Would be really cool to see Thunar support ☺️ please implement that feature sooner as you can, thanks for your work really useful tool.

**Comment by PsykeDady** [comment]
sorry for late 
the feature is ready on branch `sviluppo-filemanager`

i need only to finish the translations

**Comment by PsykeDady** [comment]
xfce thunar is now supported from commit https://github.com/PsykeDady/mowish/commit/067efd0dc9c5a1315ef09c0097d01ed6b7751e44
